#??
server:
  address: 127.0.0.1
  port: 8080

#?????
spring:
  datasource:
    name: hiquality
    url: jdbc:mysql://localhost:3306/hiquality?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #    url: jdbc:mysql://36.133.143.71:3308/hiquality?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Shanghai
    #    username: hiqgroup_root
    #    password: computer@hiqgroup123
    driverClassName: com.mysql.jdbc.Driver
  #?????
  thymeleaf:
    cache: false
    prefix: classpath:/static
    mode: HTML
    encoding: UTF-8
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

filepath:
  zyUploadPath: D:/IntelliJ/HiQuality/attach/upload
  kindEditorPath: D:/IntelliJ/HiQuality/attach/kindEditor
  templatePath: D:/IntelliJ/HiQuality/attach/template
  lucenePath: D:/IntelliJ/HiQuality/attach/lucene

###??.xml????
#mybatis.config-locations=classpath:mybatis/mybatis-config.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  ##??????
  type-aliases-package: com.hiqgroup.hiq.entity

config:
  jwt:
    # ????
    secret: adfaerwer345df2345dfghdsadfaerwer345df2345dfghds
    # token????(??)
    expire: 60
    # header ??
    header: token


logging:
  level:
    com:
      just:
        hiq:
          dao: debug
